### PR TITLE
Ci

### LINKED ISSUE #30: Travis CI integration with Docker
The tests need to be run in a docker context to ensure that the dependencies are all correct.

### PR DESCRIPTION
**Pull request by coopie**
This will resolve #30.

There is a little of my face-tracker stuff in here as I started doing this without changing branches, it 

Now we load a pre built docker image of palpitate which can be found [here](https://hub.docker.com/r/coopie/palpitate-opencv/). This makes build time around 2:30.

The container will run a test script which will contain all of our tests. Currently it just has the tests for xlsx extraction, but it is fairly straightforward to add more.

### CODE REVIEW

**Comment by kren1** [comment]
Can you squash this more?

**Comment by coopie** [comment]
removing the commits emposes my order of git commits on palpitate/master, and that is way more hassle than we need

**Comment by kren1** [comment]
Another thing. Why does this have 101k lines of code? That doesn't seem to reasonable

**Comment by coopie** [comment]
most of those lines are for the models in the face tracker

Ill remove them so its not annoying

**Pull request merged**
